# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62lock.proto\x12\rPyHealthChain\"?\n\tHashBlock\x12\x0c\n\x04hash\x18\x01 \x01(\t\x12\x11\n\tprev_hash\x18\x02 \x01(\t\x12\x11\n\tdata_hash\x18\x03 \x01(\t\"!\n\x11HashBlocksRequest\x12\x0c\n\x04hash\x18\x01 \x01(\t\"-\n\x05\x42lock\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\x14\n\x0ctransactions\x18\x02 \x01(\t\"%\n\rBlocksRequest\x12\x14\n\x0cstring_block\x18\x01 \x01(\t\"\x1a\n\x0c\x42lockRequest\x12\n\n\x02id\x18\x01 \x01(\t\"4\n\rBlockResponse\x12#\n\x05\x62lock\x18\x01 \x01(\x0b\x32\x14.PyHealthChain.Block2\xf8\x01\n\x0f\x42lockDownloader\x12L\n\rDownloadBlock\x12\x1b.PyHealthChain.BlockRequest\x1a\x1c.PyHealthChain.BlockResponse\"\x00\x12H\n\x0e\x44ownloadBlocks\x12\x1c.PyHealthChain.BlocksRequest\x1a\x14.PyHealthChain.Block\"\x00\x30\x01\x12M\n\rGetHashBlocks\x12 .PyHealthChain.HashBlocksRequest\x1a\x18.PyHealthChain.HashBlock0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'block_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HASHBLOCK']._serialized_start=30
  _globals['_HASHBLOCK']._serialized_end=93
  _globals['_HASHBLOCKSREQUEST']._serialized_start=95
  _globals['_HASHBLOCKSREQUEST']._serialized_end=128
  _globals['_BLOCK']._serialized_start=130
  _globals['_BLOCK']._serialized_end=175
  _globals['_BLOCKSREQUEST']._serialized_start=177
  _globals['_BLOCKSREQUEST']._serialized_end=214
  _globals['_BLOCKREQUEST']._serialized_start=216
  _globals['_BLOCKREQUEST']._serialized_end=242
  _globals['_BLOCKRESPONSE']._serialized_start=244
  _globals['_BLOCKRESPONSE']._serialized_end=296
  _globals['_BLOCKDOWNLOADER']._serialized_start=299
  _globals['_BLOCKDOWNLOADER']._serialized_end=547
# @@protoc_insertion_point(module_scope)
